### PR TITLE
CheckOutHandler.cs, and edited files

### PR DESCRIPTION
**Pull request by mootjso**
### **Update CheckOutHandler.cs:**
**Added methods:**
-RevenueQuarterYearIfStatement
- DetermineQuarter

**Edited method:**
- CheckOut

**RevenueQuarterYearIfStatement:**
This method will check if the movie exists inside the RevenuePerShow and if it does it will only add the money that the user now is spending.
Else if it doesnt it will bring all the details like title what quarter of the year the revenue is made and the year etc. so you can easily see what movie made how much and when.

**DetermineQuarter:**
This will determine the month / quarter it was shown as a show and place it in the json file.

**CheckOut:**
Now checks if its only number or '-' '/' where its needed.
If its a valid month I will add tonight. Not currently.

### **Edited TheaterHandler.cs:**
Added the RevenueQuarterYearIfStatement with the ticket and added money if the ticket.showid and selectedshowid are the same.

### **Edited Revenue.cs:**
New RevenueQuartly object to use later on in CheckOutHandler and fincancial report.

Also the year is given to the normal revenue object.

### CODE REVIEW

**Comment by mootjso** [comment]
:/ moet ff iets fixen omdat heel die ding weer new is :/

**Comment by mootjso** [comment]
Laat maar hij doet het wel gewoon ik was vergeten mij json files op te schonen aan mijn kant!

**Review by TriwanParagh — COMMENTED** [review]
When entering the wrong format for credit cards, you need to start from the beginning, please make it so that you don;t have to start from the beginning.

NICE QUARTERLY REVIEW!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Review by TriwanParagh — APPROVED** [review]
good

**Pull request merged**
